#!/usr/bin/env python
# -*- coding: utf-8 -*-

import types
from config_compoents import compoents_config


libs = []

# SEGGER_RTT
if get_config_val(compoents_config, 'EN_SEGGER_RTT', False) is True:
    if get_config_val(compoents_config, 'EN_SYSVIEW', False) is True:
        raise EnvironmentError(
            'ERROR:segger sysview and rtt can\'t work together for now.')

    SConscript_and_add_return_library(
        'segger_rtt_' + compoents_config.SEGGER_RTT_VERSION.lower() + '_adapter/SConscript', libs)

# REQSCHED
SConscript_and_add_return_library('reqsched/SConscript', libs)

if 0 == len(libs):
    libs = None
Return('libs')
